//= require 'libs/jquery.js'
//= require 'libs/bootstrap.min.js'
//= require 'libs/userreport.js'
//= require 'threejs/three.js'
//= require 'threejs/SimplifyModifier.js'
//= require 'threejs/stl.js'
//= require 'threejs/AugmentedConsole.js'